kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  containers:
    - name: myfrontend
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.12-alpine
      ports:
      - containerPort: 80
  nodeSelector:
    "beta.kubernetes.io/os": linux
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: functionapp
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
---
kind: Pod
apiVersion: v1
metadata:
  name: function2
  labels:
    app: functionapp
spec:
  containers:
    - name: function2
      image: crgarakspublicacr.azurecr.io/function2
      ports:
      - containerPort: 80
  nodeSelector:
    "beta.kubernetes.io/os": linux
---
apiVersion: v1
kind: Service
metadata:
  name: functionapp-service
spec:
  selector:
    app: functionapp
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
